# Generated by Django 5.1.6 on 2025-02-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('day', models.PositiveIntegerField()),
                ('month', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('item', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
